resources:
  repositories:
  - repository: vi-kube
    type: GitHub
    name: getoutreach/vi-kube
    endpoint: getoutreach

pr: none

trigger:
  branches:
    include:
    - master
  batch: true

stages:
- template: azure/templates/run_build_and_deploy.yml@vi-kube
  parameters:
    appName: kube-cleanup-operator
    rolling: False
