resources:
  repositories:
  - repository: vi-kube
    type: GitHub
    name: getoutreach/vi-kube
    endpoint: getoutreach

pr:
  branches:
    include:
    - master
    - releases/*

trigger:
  branches:
    include:
    - master
    - releases/*
  batch: true

variables:
  k8sClusterName_: $[ variables.k8sClusterName ]
  namespace_: $[ variables.namespace ]

jobs:
- template: azure/templates/run_build.yml@vi-kube
  parameters:
    appName: kube-cleanup-operator
    k8sClusterName: $(k8sClusterName_)
    namespace: $(namespace_)
