resources:
  containers:
  - container: image
    type: ACR
    azureSubscription: AzureSubscription
    resourceGroup: voice-intelligence-meeting
    registry: outreachmeeting
    repository: kube-cleanup-operator
    trigger: none

  pipelines:
  - pipeline: artifacts
    source: 'Build\kube-cleanup-operator'
    trigger: none

  repositories:
  - repository: vi-kube
    type: GitHub
    name: getoutreach/vi-kube
    endpoint: getoutreach

trigger: none
pr: none

variables:
  k8sClusterName_: $[ variables.k8sClusterName ]
  namespace_: $[ variables.namespace ]

jobs:
- template: azure/templates/run_deploy.yml@vi-kube
  parameters:
    appName: kube-cleanup-operator
    k8sClusterName: $(k8sClusterName_)
    namespace: $(namespace_)
